native RemoveVehicleComponentt(playerid, carid, component);
native InstallVehicleComponent(playerid, carid, component);
native CustomizeWheelColor(playerid, carid, wheel, color, type = 0);
native SetVinylCustomization(playerid, carid, const namecar[], color, type);
native CustomizeWheelSettings(playerid, carid, type, Float:Float_1, Float:Float_2, slot = 0);
native CustomizeCarWheel(playerid, carid, Float:Float);
native NeonColorChange(playerid, carid, color);
native SmokeColorShift(playerid, carid, color);
native SetColorHeadlamp(playerid, carid, color);
native VehicleToneCustomizer(playerid, carid, const namecar[], type, color);

